.PHONY: build clean flash

build:
	#west build -b nrf52dk/nrf52832 --sysbuild
	west build -b nrf5340_audio_dk/nrf5340/cpuapp --sysbuild

clean:
	rm -rf build


flash:
	#west flash -i 682758055
	west flash -i 1050138562


